### ISSUE TITLE
Avatar command seems to have broken bot - reverted to prev on test server

### ISSUE THREAD

**Issue by musicmaestro** [Shorthorn-Studios/Flame-bot#10]
Since avatar command included, bot no longer loads any commands in the code after that point.

Reverted back to prev. version on test server

**Comment by musicmaestro** [comment]
Quick note - we seem to be 'inlining' all of the new stuff - shouldn't it be loaded from modules to give plug and pray functionality eventually?

**Comment by Shorthorn-Studios** [comment]
Had a quick look, I would like come console logs to be able to tell what needs fixing in particular.

**Comment by musicmaestro** [comment]
Fixed this bug - but introduced another......
